<?php
/**
 * Created by PhpStorm.
 * User: lixingbo
 * Date: 2019/2/22
 * Time: 下午1:41
 */

namespace Ddup\Part\Response;


use Illuminate\Contracts\Support\Arrayable;

class Response extends \Illuminate\Http\Response
{
    private $_code   = 'success';
    private $_msg;
    private $_data;
    private $_extend = [];

    private $_code_success = 'success';

    function data($data)
    {
        if ($data instanceof Arrayable) {
            $data = $data->toArray();
        }

        $this->_data = $data;

        return self::updateContent();
    }

    function code($code)
    {
        $this->_code = $code;

        return self::updateContent();
    }

    function success()
    {
        $this->_code = $this->_code_success;

        return self::updateContent();
    }

    function isSuccess()
    {
        return $this->_code == $this->_code_success;
    }

    function fail()
    {
        $this->_code = 'fail';

        return self::updateContent();
    }

    function message($msg)
    {
        $this->_msg = $msg;

        return self::updateContent();
    }

    function msg($msg)
    {
        return self::message($msg);
    }

    private function updateContent()
    {
        parent::setContent($this->completeContent());

        return $this;
    }

    public function setContent($content)
    {
        if ($this->shouldBeJson($content)) {
            $this->_data = $content;
        }

        return parent::setContent($this->completeContent()); // TODO: Change the autogenerated stub
    }

    public function extends(array $param)
    {
        $this->_extend = array_diff_key($param, ['retcode' => '', 'msg' => '', 'data' => '']);

        return $this->updateContent();
    }

    private function completeContent()
    {
        return array_merge([
            'retcode' => $this->_code,
            'msg'     => $this->_msg,
            'data'    => $this->_data
        ], $this->_extend);
    }
}